name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 저장소 코드 불러오기
      uses: actions/checkout@v4
      
    - name: 파이썬 환경 설정
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: 패키지 설치 및 환경 검증
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 1. 테스트 실행 전에 가상 환경에서 데이터를 만들고 모델을 학습시켜 mlflow.db를 생성함
    - name: Train Model for Testing
      run: |
        python -m ml.train
      env:
        MLFLOW_URL: "sqlite:///mlflow.db"

    # 2. 기존 테스트 단계에 모델 로드와 깃허브 이슈 생성을 위한 환경 변수 주입
    - name: Run Tests with pytest
      run: |
        python -m pytest tests/
      env:
        GH_REPO: ${{ secrets.GH_REPO }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        MLFLOW_URL: "sqlite:///mlflow.db"

    - name: Build Docker Image
      run: |
        docker build -t flask-image-app .